/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/Demon.gltf -o src/components/Demon.jsx 
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Demon({ hovered, name, ...props }) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/Demon.gltf");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  console.log("Demon", actions);

  useEffect(() => {
    const activeAnim = name === "Demon 1" ? "Yes" : "Wave";
    const anim = hovered ? activeAnim : "Idle";

    actions[anim].reset().fadeIn(0.5).play();

    return () => actions[anim].reset().fadeOut(0.5);
  }, [hovered]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <skinnedMesh name="Demon" geometry={nodes.Demon.geometry} material={materials.Atlas} skeleton={nodes.Demon.skeleton} />
          <skinnedMesh name="Trident" geometry={nodes.Trident.geometry} material={materials.Atlas} skeleton={nodes.Trident.skeleton} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Demon.gltf");
