/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/Ninja.gltf -o src/components/Ninja.jsx 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Ninja(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/Ninja.gltf");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <skinnedMesh name="Ninja" geometry={nodes.Ninja.geometry} material={materials.Atlas} skeleton={nodes.Ninja.skeleton} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Ninja.gltf");
